const actions = {
  MOVIES_REQUEST: 'MOVIES_REQUEST',
  MOVIES_SUCCESS: 'MOVIES_SUCCESS',
  MOVIES_ERROR: 'MOVIES_ERROR',
  SEARCH_REQUEST: 'SEARCH_REQUEST',
  SEARCH_SUCCESS: 'SEARCH_SUCCESS',
  SEARCH_ERROR: 'SEARCH_ERROR',
  DETAIL_MOVIE_REQUEST: 'DETAIL_MOVIE_REQUEST',
  DETAIL_MOVIE_SUCCESS: 'DETAIL_MOVIE_SUCCESS',
  DETAIL_MOVIE_ERROR: 'DETAIL_MOVIE_ERROR',
};

export default actions;
